### ISSUE TITLE
Evaluation in Metaworld task

### ISSUE THREAD

**Issue by fuyw** [dwjshift/IL_ADS#1]
Hello,

I have some questions about the evaluation in the Metaworld environment.

- The training environment and the evaluation environment are exactly the same?

https://github.com/dwjshift/IL_ADS/blob/4e478b802dca280bd3efa731eb4f11941329f659/IL/train.py#L98

https://github.com/dwjshift/IL_ADS/blob/4e478b802dca280bd3efa731eb4f11941329f659/IL/train.py#L99

- We define one trajectory to be successful if there are more than 3 successful states?

https://github.com/dwjshift/IL_ADS/blob/4e478b802dca280bd3efa731eb4f11941329f659/IL/train.py#L176

So, it's likely the task is actually not solved at the last time step? For example, the arm first opens the door and then closes it?

- ADS uses evaluation trajectory information to update the adaptive discount scheduler?

https://github.com/dwjshift/IL_ADS/blob/4e478b802dca280bd3efa731eb4f11941329f659/IL/train.py#L188

If so, then ADS uses more online environmental steps than the other baselines.

**Comment by dwjshift** [comment]
Hi fuyw,
1. Yes. And both environments have random initialization.
2. Following previous work, we mark a trajectory as successful if the agent experiences >3 successful states. In the collected expert demos, the expert will stay at the successful state for the last >=10 steps. Hence it's unlikely that the agent will eventually learn to move back to an unsuccessful state after it finishes the task.
3. Thank you for pointing out this small oversight. As these evaluation trajectories provide only 10%+ additional env frames (we evaluate 10 trajectories every 10000 env frames) and they are not used to update the agent's networks, we believe this will not change the conclusions in our paper.

**Comment by fuyw** [comment]
Thanks for the reply. I still have a question about the first point. Since we use the environment from the `ml1.train_tasks`.

```
# Set random goal
task = random.choice(self.ml1.train_tasks)
self._env.set_task(task)  # Set task
```

So there are all together 50 different random initializations? The agent has already seen each possible initialization for many times during the training.

**Comment by dwjshift** [comment]
Yes. We simply follow the setting of the [baseline.](https://github.com/siddhanthaldar/ROT)

**Comment by fuyw** [comment]
I see. Thanks.

**Comment by fuyw** [comment]
Actually, it's a little bit tricky for the second point. In short, this depends on task.

I just checked the `pick-place-wall-v3` task. If we follow the definition in metaworld: the task is solved when the red cylinder is moved to the blue point position.

Then the current ADS agent actually doesn't solve the task at the last step. The arm will move to the blue point position, and then drops the red cylinder. If we can use the sparse task reward then this is not an issue. Otherwise, it will be a little bit tricky.

**Comment by dwjshift** [comment]
Thank you for your additional comment.
In fact, in the last few frames of the expert demonstration of the `pick-place-wall-v3` task, the cylinder is almost hidden behind the wall. (See the following figure.) Since our setting is learning from visual demonstrations, the agent can't know whether to drop the cylinder or keep it up. I think this issue can be simply addressed if we use a better camera view.
![pick-place-wall](https://github.com/dwjshift/IL_ADS/assets/50415221/7a5c2ae6-3263-4198-a9d4-df231f0cec28)

**Comment by fuyw** [comment]
That's an interesting point. What if the demonstrations are from some different camera views? I think the fixed camera view to be less practical in the real-world application. And imitation learning from multi-view demonstrations could be much harder than the current setting.

**Comment by dwjshift** [comment]
Good question. We haven't tried that yet. Feel free to try it out if you're interested :)
